/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary-container': '#016d7a',
        'on-tertiary-fixed': '#2e1600',
        'surface-bright': '#f7f9fb',
        'on-primary-fixed': '#001d32',
        'surface': '#f7f9fb',
        'on-error': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fff6f1',
        'surface-dim': '#d8dadc',
        'secondary-fixed': '#9feffe',
        'on-primary-fixed-variant': '#004b74',
        'tertiary-container': '#a95f00',
        'error-container': '#ffdad6',
        'surface-container-highest': '#e0e3e5',
        'primary-container': '#0077b6',
        'tertiary-fixed-dim': '#ffb877',
        'on-primary': '#ffffff',
        'secondary-fixed-dim': '#83d3e1',
        'outline': '#707881',
        'inverse-primary': '#94ccff',
        'tertiary-fixed': '#ffdcc0',
        'on-secondary': '#ffffff',
        'primary': '#005d90',
        'on-background': '#191c1e',
        'surface-tint': '#006399',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'background': '#f7f9fb',
        'on-tertiary-fixed-variant': '#6c3a00',
        'on-error-container': '#93000a',
        'surface-container': '#eceef0',
        'inverse-surface': '#2d3133',
        'primary-fixed': '#cde5ff',
        'on-primary-container': '#f3f7ff',
        'on-secondary-fixed-variant': '#004f59',
        'inverse-on-surface': '#eff1f3',
        'on-surface': '#191c1e',
        'outline-variant': '#bfc7d1',
        'tertiary': '#864a00',
        'on-surface-variant': '#404850',
        'on-secondary-fixed': '#001f24',
        'secondary-container': '#9cecfb',
        'surface-container-high': '#e6e8ea',
        'secondary': '#006875',
        'error': '#ba1a1a',
        'surface-variant': '#e0e3e5',
        'primary-fixed-dim': '#94ccff',
      },
      fontFamily: {
        'headline': ['Manrope'],
        'body': ['Inter'],
        'label': ['Inter'],
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
